# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.inline_response200587 import InlineResponse200587

class TestInlineResponse200587(unittest.TestCase):
    """InlineResponse200587 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineResponse200587:
        """Test InlineResponse200587
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineResponse200587`
        """
        model = InlineResponse200587()
        if include_optional:
            return InlineResponse200587(
                apiversion = 3,
                func = 'get_php_recommendations',
                module = 'EA4',
                result = clientapi_cpanel.models.inline_response_200_587_result.inline_response_200_587_result(
                    data = [
                        'php80'
                        ], 
                    errors = [
                        ''
                        ], 
                    messages = [
                        ''
                        ], 
                    metadata = clientapi_cpanel.models.inline_response_200_result_metadata.inline_response_200_result_metadata(
                        transformed = 1, ), 
                    status = 1, 
                    warnings = [
                        ''
                        ], )
            )
        else:
            return InlineResponse200587(
        )
        """

    def testInlineResponse200587(self):
        """Test InlineResponse200587"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
