# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.part import Part

class TestPart(unittest.TestCase):
    """Part unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPart(self):
        """Test Part"""
        # inst = Part()

if __name__ == '__main__':
    unittest.main()
