# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.inline_response20093 import InlineResponse20093

class TestInlineResponse20093(unittest.TestCase):
    """InlineResponse20093 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineResponse20093:
        """Test InlineResponse20093
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineResponse20093`
        """
        model = InlineResponse20093()
        if include_optional:
            return InlineResponse20093(
                apiversion = 3,
                func = 'export_zone_dnskey',
                module = 'DNSSEC',
                result = clientapi_cpanel.models.inline_response_200_93_result.inline_response_200_93_result(
                    data = clientapi_cpanel.models.inline_response_200_93_result_data.inline_response_200_93_result_data(
                        dnskey = 'AwEAAch8SGW4vE6PjFWA9rbUm0AfTq+gJ0HC/nLu+2axdWHBIStt9lsOzKDorAr4vlmhlJzEzA62s96xp6mZ7XHUyWnkFwLs8obo6upL2in4h1ToOxzVl3lTs8O+kWtDq5/h1nwFlPDs9zpLJhlkTCtx2OTGbvimEYeqwPolUuSQR/Yb', 
                        key_id = 12345, 
                        success = 1, ), 
                    errors = [
                        ''
                        ], 
                    messages = [
                        ''
                        ], 
                    metadata = null, 
                    status = 1, 
                    warnings = [
                        ''
                        ], )
            )
        else:
            return InlineResponse20093(
        )
        """

    def testInlineResponse20093(self):
        """Test InlineResponse20093"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
