# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.api.mail_server_information_api import MailServerInformationApi


class TestMailServerInformationApi(unittest.TestCase):
    """MailServerInformationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MailServerInformationApi()

    def tearDown(self) -> None:
        pass

    def test_get_exim_ports(self) -> None:
        """Test case for get_exim_ports

        Return outgoing (SMTP) mail port
        """
        pass

    def test_get_exim_ports_ssl(self) -> None:
        """Test case for get_exim_ports_ssl

        Return outgoing mail (SMTP) SSL-secured port
        """
        pass


if __name__ == '__main__':
    unittest.main()
