# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.inline_response200528 import InlineResponse200528

class TestInlineResponse200528(unittest.TestCase):
    """InlineResponse200528 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineResponse200528:
        """Test InlineResponse200528
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineResponse200528`
        """
        model = InlineResponse200528()
        if include_optional:
            return InlineResponse200528(
                apiversion = 3,
                func = 'create_user',
                module = 'UserManager',
                result = clientapi_cpanel.models.inline_response_200_528_result.inline_response_200_528_result(
                    data = null, 
                    errors = [
                        ''
                        ], 
                    messages = [
                        ''
                        ], 
                    metadata = null, 
                    status = 1, 
                    warnings = [
                        ''
                        ], )
            )
        else:
            return InlineResponse200528(
        )
        """

    def testInlineResponse200528(self):
        """Test InlineResponse200528"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
