# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.inline_response200280 import InlineResponse200280

class TestInlineResponse200280(unittest.TestCase):
    """InlineResponse200280 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineResponse200280:
        """Test InlineResponse200280
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineResponse200280`
        """
        model = InlineResponse200280()
        if include_optional:
            return InlineResponse200280(
                apiversion = 3,
                func = 'php_get_impacted_domains',
                module = 'LangPHP',
                result = clientapi_cpanel.models.inline_response_200_280_result.inline_response_200_280_result(
                    data = clientapi_cpanel.models.inline_response_200_280_result_data.inline_response_200_280_result_data(
                        domains = [
                            'example.com'
                            ], ), 
                    errors = [
                        ''
                        ], 
                    messages = [
                        ''
                        ], 
                    metadata = null, 
                    status = 1, 
                    warnings = [
                        ''
                        ], )
            )
        else:
            return InlineResponse200280(
        )
        """

    def testInlineResponse200280(self):
        """Test InlineResponse200280"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
