# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.api.file_restoration_api import FileRestorationApi


class TestFileRestorationApi(unittest.TestCase):
    """FileRestorationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FileRestorationApi()

    def tearDown(self) -> None:
        pass

    def test_directory_listing(self) -> None:
        """Test case for directory_listing

        Return backups in home directory
        """
        pass

    def test_get_users(self) -> None:
        """Test case for get_users

        Return cPanel accounts with backup metadata
        """
        pass

    def test_query_file_info(self) -> None:
        """Test case for query_file_info

        Return backup storage locations
        """
        pass

    def test_restore_databases(self) -> None:
        """Test case for restore_databases

        Restore databases
        """
        pass

    def test_restore_email_filters(self) -> None:
        """Test case for restore_email_filters

        Restore email filters
        """
        pass

    def test_restore_email_forwarders(self) -> None:
        """Test case for restore_email_forwarders

        Restore email forwarders
        """
        pass

    def test_restore_file(self) -> None:
        """Test case for restore_file

        Restore file or directory
        """
        pass

    def test_restore_files(self) -> None:
        """Test case for restore_files

        Restore files
        """
        pass


if __name__ == '__main__':
    unittest.main()
