# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.inline_response200502 import InlineResponse200502

class TestInlineResponse200502(unittest.TestCase):
    """InlineResponse200502 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineResponse200502:
        """Test InlineResponse200502
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineResponse200502`
        """
        model = InlineResponse200502()
        if include_optional:
            return InlineResponse200502(
                apiversion = 3,
                func = 'password_reset_request',
                module = 'Team',
                result = clientapi_cpanel.models.inline_response_200_496_result.inline_response_200_496_result(
                    data = clientapi_cpanel.models.data.data(), 
                    errors = [
                        ''
                        ], 
                    messages = [
                        ''
                        ], 
                    metadata = clientapi_cpanel.models.inline_response_200_result_metadata.inline_response_200_result_metadata(
                        transformed = 1, ), 
                    status = 1, 
                    warnings = [
                        ''
                        ], )
            )
        else:
            return InlineResponse200502(
        )
        """

    def testInlineResponse200502(self):
        """Test InlineResponse200502"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
