# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.api.directory_protection_api import DirectoryProtectionApi


class TestDirectoryProtectionApi(unittest.TestCase):
    """DirectoryProtectionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DirectoryProtectionApi()

    def tearDown(self) -> None:
        pass

    def test_directory_protection_list_directories(self) -> None:
        """Test case for directory_protection_list_directories

        Return Directory Protection settings
        """
        pass


if __name__ == '__main__':
    unittest.main()
