# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.inline_response200106 import InlineResponse200106

class TestInlineResponse200106(unittest.TestCase):
    """InlineResponse200106 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineResponse200106:
        """Test InlineResponse200106
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineResponse200106`
        """
        model = InlineResponse200106()
        if include_optional:
            return InlineResponse200106(
                apiversion = 3,
                func = 'is_directory_protected',
                module = 'DirectoryPrivacy',
                result = clientapi_cpanel.models.inline_response_200_106_result.inline_response_200_106_result(
                    data = clientapi_cpanel.models.inline_response_200_106_result_data.inline_response_200_106_result_data(
                        auth_name = 'Protected 'example.com'', 
                        auth_type = 'Basic', 
                        passwd_file = '/home/example/.htpasswds/example.com/passwd', 
                        protected = 1, ), 
                    errors = [
                        ''
                        ], 
                    messages = [
                        ''
                        ], 
                    metadata = null, 
                    status = 1, 
                    warnings = [
                        ''
                        ], )
            )
        else:
            return InlineResponse200106(
        )
        """

    def testInlineResponse200106(self):
        """Test InlineResponse200106"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
