# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.team_hash_users_info import TeamHashUsersInfo

class TestTeamHashUsersInfo(unittest.TestCase):
    """TeamHashUsersInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamHashUsersInfo:
        """Test TeamHashUsersInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TeamHashUsersInfo`
        """
        model = TeamHashUsersInfo()
        if include_optional:
            return TeamHashUsersInfo(
                contact_email = 'team_user@example.com',
                created = 1650036110,
                expire_date = 1674575562,
                expire_reason = 'team user 1 year',
                lastlogin = 1650046110,
                locale = 'en',
                notes = 'This is a note about team_user.',
                password = 'encryptedpassword',
                roles = [
                    'email,web'
                    ],
                secondary_contact_email = 'team_user_backup@example.com',
                services = clientapi_cpanel.models.services.Services(
                    email = '500*2**20', 
                    ftp = 1, 
                    webdisk = 'rw', ),
                suspend_date = '',
                suspend_reason = 'teamUser is on vacation'
            )
        else:
            return TeamHashUsersInfo(
        )
        """

    def testTeamHashUsersInfo(self):
        """Test TeamHashUsersInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
