# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.api.bandwidth_api import BandwidthApi


class TestBandwidthApi(unittest.TestCase):
    """BandwidthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BandwidthApi()

    def tearDown(self) -> None:
        pass

    def test_get_enabled_protocols(self) -> None:
        """Test case for get_enabled_protocols

        Return services monitored in bandwidth data
        """
        pass

    def test_get_retention_periods(self) -> None:
        """Test case for get_retention_periods

        Return bandwidth retention period
        """
        pass

    def test_query(self) -> None:
        """Test case for query

        Return cPanel account's bandwidth usage report
        """
        pass


if __name__ == '__main__':
    unittest.main()
