# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.inline_response20042 import InlineResponse20042

class TestInlineResponse20042(unittest.TestCase):
    """InlineResponse20042 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineResponse20042:
        """Test InlineResponse20042
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineResponse20042`
        """
        model = InlineResponse20042()
        if include_optional:
            return InlineResponse20042(
                apiversion = 3,
                func = 'get_application_information',
                module = 'Branding',
                result = clientapi_cpanel.models.inline_response_200_42_result.inline_response_200_42_result(
                    data = clientapi_cpanel.models.inline_response_200_42_result_data.inline_response_200_42_result_data(
                        feature = 'boxtrapper', 
                        file = 'boxtrapper', 
                        group = 'mail', 
                        height = 32, 
                        if = '$hasboxtrapper', 
                        imgtype = 'icon', 
                        itemdesc = 'BoxTrapper', 
                        itemorder = 3, 
                        module = 'BoxTrapper', 
                        searchtext = 'boxtrapper', 
                        subtype = 'img', 
                        type = 'image', 
                        url = 'mail/boxtrapper.html', 
                        width = 35, ), 
                    errors = [
                        ''
                        ], 
                    messages = [
                        ''
                        ], 
                    metadata = null, 
                    status = 1, 
                    warnings = [
                        ''
                        ], )
            )
        else:
            return InlineResponse20042(
        )
        """

    def testInlineResponse20042(self):
        """Test InlineResponse20042"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
