# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.inline_response200489 import InlineResponse200489

class TestInlineResponse200489(unittest.TestCase):
    """InlineResponse200489 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineResponse200489:
        """Test InlineResponse200489
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineResponse200489`
        """
        model = InlineResponse200489()
        if include_optional:
            return InlineResponse200489(
                apiversion = 3,
                func = 'get_site_errors',
                module = 'Stats',
                result = clientapi_cpanel.models.inline_response_200_489_result.inline_response_200_489_result(
                    data = [
                        clientapi_cpanel.models.inline_response_200_489_result_data.inline_response_200_489_result_data(
                            date = 1234576704, 
                            entry = '[Fri Feb 13 19:58:24.420593 2009] [core:error] [pid 29228:tid 47876185720577] (13)Permission denied: [client 10.0.0.2:62908] AH00132: file permissions deny server access: /home/user/public_html/index.html', )
                        ], 
                    errors = [
                        ''
                        ], 
                    messages = [
                        ''
                        ], 
                    metadata = clientapi_cpanel.models.inline_response_200_result_metadata.inline_response_200_result_metadata(
                        transformed = 1, ), 
                    status = 1, 
                    warnings = [
                        ''
                        ], )
            )
        else:
            return InlineResponse200489(
        )
        """

    def testInlineResponse200489(self):
        """Test InlineResponse200489"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
