# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.api.mailing_lists_api import MailingListsApi


class TestMailingListsApi(unittest.TestCase):
    """MailingListsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MailingListsApi()

    def tearDown(self) -> None:
        pass

    def test_add_list(self) -> None:
        """Test case for add_list

        Create mailing list
        """
        pass

    def test_add_mailman_delegates(self) -> None:
        """Test case for add_mailman_delegates

        Add administrators to mailing list
        """
        pass

    def test_count_lists(self) -> None:
        """Test case for count_lists

        Return cPanel account's mailing list total
        """
        pass

    def test_delete_list(self) -> None:
        """Test case for delete_list

        Delete mailing list
        """
        pass

    def test_export_lists(self) -> None:
        """Test case for export_lists

        Export cPanel account's Mailman mailing lists to a file
        """
        pass

    def test_generate_mailman_otp(self) -> None:
        """Test case for generate_mailman_otp

        Create one-time password for a mailing list
        """
        pass

    def test_get_lists_total_disk_usage(self) -> None:
        """Test case for get_lists_total_disk_usage

        Return cPanel account's mailing list disk usage
        """
        pass

    def test_get_mailman_delegates(self) -> None:
        """Test case for get_mailman_delegates

        Return mailing list administrators
        """
        pass

    def test_has_delegated_mailman_lists(self) -> None:
        """Test case for has_delegated_mailman_lists

        Return email account's mailing list privileges
        """
        pass

    def test_list_lists(self) -> None:
        """Test case for list_lists

        Return cPanel account's mailing lists
        """
        pass

    def test_passwd_list(self) -> None:
        """Test case for passwd_list

        Update mailing list password
        """
        pass

    def test_remove_mailman_delegates(self) -> None:
        """Test case for remove_mailman_delegates

        Remove account mailing list admin privileges
        """
        pass

    def test_set_list_privacy_options(self) -> None:
        """Test case for set_list_privacy_options

        Update mailing list privacy options
        """
        pass


if __name__ == '__main__':
    unittest.main()
