# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.api.calendar_and_contacts_server_api import CalendarAndContactsServerApi


class TestCalendarAndContactsServerApi(unittest.TestCase):
    """CalendarAndContactsServerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CalendarAndContactsServerApi()

    def tearDown(self) -> None:
        pass

    def test_add_delegate(self) -> None:
        """Test case for add_delegate

        Add calendar delegation
        """
        pass

    def test_list_delegates(self) -> None:
        """Test case for list_delegates

        List cPanel account's calendar delegates
        """
        pass

    def test_list_users(self) -> None:
        """Test case for list_users

        List cPanel account's calendar users
        """
        pass

    def test_remove_delegate(self) -> None:
        """Test case for remove_delegate

        Remove calendar delegation
        """
        pass

    def test_update_delegate(self) -> None:
        """Test case for update_delegate

        Update calendar delegation
        """
        pass


if __name__ == '__main__':
    unittest.main()
