# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.api.url_parsing_api import URLParsingApi


class TestURLParsingApi(unittest.TestCase):
    """URLParsingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = URLParsingApi()

    def tearDown(self) -> None:
        pass

    def test_fetch_url(self) -> None:
        """Test case for fetch_url

        Return integrated application URL
        """
        pass

    def test_firstfile_relative_uri(self) -> None:
        """Test case for firstfile_relative_uri

        Return session relative URI
        """
        pass


if __name__ == '__main__':
    unittest.main()
