# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.inline_response200303 import InlineResponse200303

class TestInlineResponse200303(unittest.TestCase):
    """InlineResponse200303 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineResponse200303:
        """Test InlineResponse200303
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineResponse200303`
        """
        model = InlineResponse200303()
        if include_optional:
            return InlineResponse200303(
                apiversion = 3,
                func = 'create_shopping_cart',
                module = 'Market',
                result = clientapi_cpanel.models.inline_response_200_303_result.inline_response_200_303_result(
                    data = clientapi_cpanel.models.inline_response_200_303_result_data.inline_response_200_303_result_data(
                        checkout_url = 'http://www.example.com/checkout', 
                        order_id = '8765309', 
                        order_items = [
                            None
                            ], ), 
                    errors = [
                        ''
                        ], 
                    messages = [
                        ''
                        ], 
                    metadata = null, 
                    status = 1, 
                    warnings = [
                        ''
                        ], )
            )
        else:
            return InlineResponse200303(
        )
        """

    def testInlineResponse200303(self):
        """Test InlineResponse200303"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
