# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.service_account_services_email import ServiceAccountServicesEmail

class TestServiceAccountServicesEmail(unittest.TestCase):
    """ServiceAccountServicesEmail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceAccountServicesEmail:
        """Test ServiceAccountServicesEmail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceAccountServicesEmail`
        """
        model = ServiceAccountServicesEmail()
        if include_optional:
            return ServiceAccountServicesEmail(
                enabled = 1,
                quota = 100
            )
        else:
            return ServiceAccountServicesEmail(
        )
        """

    def testServiceAccountServicesEmail(self):
        """Test ServiceAccountServicesEmail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
