# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.api.ssl_certificate_management_api import SSLCertificateManagementApi


class TestSSLCertificateManagementApi(unittest.TestCase):
    """SSLCertificateManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SSLCertificateManagementApi()

    def tearDown(self) -> None:
        pass

    def test_delete_cert(self) -> None:
        """Test case for delete_cert

        Delete SSL certificate
        """
        pass

    def test_delete_csr(self) -> None:
        """Test case for delete_csr

        Delete certificate signing request
        """
        pass

    def test_delete_key(self) -> None:
        """Test case for delete_key

        Delete private key
        """
        pass

    def test_generate_cert(self) -> None:
        """Test case for generate_cert

        Create self-signed SSL certificate
        """
        pass

    def test_generate_csr(self) -> None:
        """Test case for generate_csr

        Create certificate signing request
        """
        pass

    def test_install_ssl(self) -> None:
        """Test case for install_ssl

        Install SSL certificate
        """
        pass

    def test_s_sl_generate_key(self) -> None:
        """Test case for s_sl_generate_key

        Create private key
        """
        pass

    def test_set_cert_friendly_name(self) -> None:
        """Test case for set_cert_friendly_name

        Update SSL certificate's friendly name
        """
        pass

    def test_set_csr_friendly_name(self) -> None:
        """Test case for set_csr_friendly_name

        Update certificate signing request's friendly name
        """
        pass

    def test_set_key_friendly_name(self) -> None:
        """Test case for set_key_friendly_name

        Update private key's friendly name
        """
        pass

    def test_set_primary_ssl(self) -> None:
        """Test case for set_primary_ssl

        Update SSL website for dedicated IP address
        """
        pass

    def test_show_cert(self) -> None:
        """Test case for show_cert

        Export SSL certificate
        """
        pass

    def test_show_csr(self) -> None:
        """Test case for show_csr

        Export certificate signing request
        """
        pass

    def test_show_key(self) -> None:
        """Test case for show_key

        Export private key
        """
        pass

    def test_upload_cert(self) -> None:
        """Test case for upload_cert

        Import SSL certificate
        """
        pass

    def test_upload_key(self) -> None:
        """Test case for upload_key

        Import private key
        """
        pass


if __name__ == '__main__':
    unittest.main()
