# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.api.web_disk_api import WebDiskApi


class TestWebDiskApi(unittest.TestCase):
    """WebDiskApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebDiskApi()

    def tearDown(self) -> None:
        pass

    def test_set_permissions(self) -> None:
        """Test case for set_permissions

        Update Web Disk home directory permissions
        """
        pass

    def test_web_disk_delete_user(self) -> None:
        """Test case for web_disk_delete_user

        Delete Web Disk account
        """
        pass

    def test_web_disk_set_homedir(self) -> None:
        """Test case for web_disk_set_homedir

        Update Web Disk home directory location
        """
        pass

    def test_web_disk_set_password(self) -> None:
        """Test case for web_disk_set_password

        Update Web Disk account password
        """
        pass


if __name__ == '__main__':
    unittest.main()
