# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.inline_response200273 import InlineResponse200273

class TestInlineResponse200273(unittest.TestCase):
    """InlineResponse200273 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineResponse200273:
        """Test InlineResponse200273
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineResponse200273`
        """
        model = InlineResponse200273()
        if include_optional:
            return InlineResponse200273(
                apiversion = 3,
                func = 'resize_image',
                module = 'ImageManager',
                result = clientapi_cpanel.models.inline_response_200_273_result.inline_response_200_273_result(
                    data = '/home/cptest1/images/myimage.jpg', 
                    errors = [
                        ''
                        ], 
                    messages = [
                        ''
                        ], 
                    metadata = null, 
                    status = 1, 
                    warnings = [
                        ''
                        ], )
            )
        else:
            return InlineResponse200273(
        )
        """

    def testInlineResponse200273(self):
        """Test InlineResponse200273"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
