# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.api.account_information_api import AccountInformationApi


class TestAccountInformationApi(unittest.TestCase):
    """AccountInformationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountInformationApi()

    def tearDown(self) -> None:
        pass

    def test_list_accounts(self) -> None:
        """Test case for list_accounts

        Return reseller's cPanel accounts
        """
        pass

    def test_variables_get_user_information(self) -> None:
        """Test case for variables_get_user_information

        Return cPanel account's configuration settings
        """
        pass


if __name__ == '__main__':
    unittest.main()
