# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.inline_response200254 import InlineResponse200254

class TestInlineResponse200254(unittest.TestCase):
    """InlineResponse200254 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineResponse200254:
        """Test InlineResponse200254
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineResponse200254`
        """
        model = InlineResponse200254()
        if include_optional:
            return InlineResponse200254(
                apiversion = 3,
                func = 'list_ftp_with_disk',
                module = 'Ftp',
                result = clientapi_cpanel.models.inline_response_200_254_result.inline_response_200_254_result(
                    data = [
                        clientapi_cpanel.models.inline_response_200_254_result_data.inline_response_200_254_result_data(
                            _diskquota = '476.84', 
                            _diskused = '2.34', 
                            accttype = 'sub', 
                            deleteable = 1, 
                            dir = '/home/user/public_ftp', 
                            diskquota = 476.84, 
                            diskused = '2.34', 
                            diskusedpercent = 21, 
                            diskusedpercent20 = 20, 
                            htmldir = '', 
                            humandiskquota = '477 MB', 
                            humandiskused = '2 MB', 
                            login = 'ftpaccount', 
                            reldir = 'public_ftp', 
                            serverlogin = 'ftpaccount@example.com', )
                        ], 
                    errors = [
                        ''
                        ], 
                    messages = [
                        ''
                        ], 
                    metadata = clientapi_cpanel.models.inline_response_200_result_metadata.inline_response_200_result_metadata(
                        transformed = 1, ), 
                    status = 1, 
                    warnings = [
                        ''
                        ], )
            )
        else:
            return InlineResponse200254(
        )
        """

    def testInlineResponse200254(self):
        """Test InlineResponse200254"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
