# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.inline_response200250 import InlineResponse200250

class TestInlineResponse200250(unittest.TestCase):
    """InlineResponse200250 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineResponse200250:
        """Test InlineResponse200250
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineResponse200250`
        """
        model = InlineResponse200250()
        if include_optional:
            return InlineResponse200250(
                apiversion = 3,
                func = 'get_quota',
                module = 'Ftp',
                result = clientapi_cpanel.models.inline_response_200_250_result.inline_response_200_250_result(
                    data = 'unlimited', 
                    errors = [
                        ''
                        ], 
                    messages = [
                        ''
                        ], 
                    metadata = null, 
                    status = 1, 
                    warnings = [
                        ''
                        ], )
            )
        else:
            return InlineResponse200250(
        )
        """

    def testInlineResponse200250(self):
        """Test InlineResponse200250"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
