# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.inline_response200402 import InlineResponse200402

class TestInlineResponse200402(unittest.TestCase):
    """InlineResponse200402 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineResponse200402:
        """Test InlineResponse200402
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineResponse200402`
        """
        model = InlineResponse200402()
        if include_optional:
            return InlineResponse200402(
                apiversion = 3,
                func = 'add_autossl_excluded_domains',
                module = 'SSL',
                result = clientapi_cpanel.models.inline_response_200_120_result.inline_response_200_120_result(
                    data = clientapi_cpanel.models.data.data(), 
                    errors = [
                        ''
                        ], 
                    messages = [
                        ''
                        ], 
                    metadata = null, 
                    status = 1, 
                    warnings = [
                        ''
                        ], )
            )
        else:
            return InlineResponse200402(
        )
        """

    def testInlineResponse200402(self):
        """Test InlineResponse200402"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
