# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.main_domain_contents import MainDomainContents

class TestMainDomainContents(unittest.TestCase):
    """MainDomainContents unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MainDomainContents:
        """Test MainDomainContents
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MainDomainContents`
        """
        model = MainDomainContents()
        if include_optional:
            return MainDomainContents(
                all_aliases_valid = 1,
                can_https_redirect = 1,
                customlog = clientapi_cpanel.models.main_domain_contents_customlog.MainDomainContents_customlog(
                    format = '', 
                    target = '', ),
                documentroot = '',
                domain = '',
                group = '',
                hascgi = 1,
                homedir = '',
                ifmodulemodsuphpc = clientapi_cpanel.models.main_domain_contents_ifmodulemodsuphpc.MainDomainContents_ifmodulemodsuphpc(
                    group = '', ),
                ip = '',
                ipv6 = '',
                is_https_redirecting = 1,
                no_cache_update = 1,
                owner = '',
                scriptalias = clientapi_cpanel.models.main_domain_contents_scriptalias.MainDomainContents_scriptalias(
                    path = '', 
                    url = '', ),
                serveradmin = '',
                serveralias = '',
                servername = '',
                type = 'main_domain',
                usecanonicalname = 'On',
                user = '',
                userdirprotect = 1
            )
        else:
            return MainDomainContents(
        )
        """

    def testMainDomainContents(self):
        """Test MainDomainContents"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
