# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.api.browser_cache_management_api import BrowserCacheManagementApi


class TestBrowserCacheManagementApi(unittest.TestCase):
    """BrowserCacheManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BrowserCacheManagementApi()

    def tearDown(self) -> None:
        pass

    def test_cache_buster_read(self) -> None:
        """Test case for cache_buster_read

        Return web browser cached file override ID
        """
        pass

    def test_update(self) -> None:
        """Test case for update

        Create web browser cached file override ID
        """
        pass


if __name__ == '__main__':
    unittest.main()
