# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.inline_response20048 import InlineResponse20048

class TestInlineResponse20048(unittest.TestCase):
    """InlineResponse20048 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineResponse20048:
        """Test InlineResponse20048
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineResponse20048`
        """
        model = InlineResponse20048()
        if include_optional:
            return InlineResponse20048(
                apiversion = 3,
                func = 'list_users',
                module = 'CCS',
                result = clientapi_cpanel.models.inline_response_200_48_result.inline_response_200_48_result(
                    data = {"user1@example.com":"0882362A-0B98-11E8-BAF5-D988266709C1","user2@example.com":"96F1EB2F-A501-11EA-A3EF-A553B2E4FFA8","user3@example.com":"195C8A51-E1B3-11E6-8715-F54FA4E00DDD","user4@example.com":"028F4AB1-0F1A-11E7-AEC7-E08FECEC8036"}, 
                    errors = [
                        ''
                        ], 
                    messages = [
                        ''
                        ], 
                    metadata = null, 
                    status = 1, 
                    warnings = [
                        ''
                        ], )
            )
        else:
            return InlineResponse20048(
        )
        """

    def testInlineResponse20048(self):
        """Test InlineResponse20048"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
