# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.inline_response20060 import InlineResponse20060

class TestInlineResponse20060(unittest.TestCase):
    """InlineResponse20060 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineResponse20060:
        """Test InlineResponse20060
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineResponse20060`
        """
        model = InlineResponse20060()
        if include_optional:
            return InlineResponse20060(
                apiversion = 3,
                func = 'get_exim_ports',
                module = 'Chkservd',
                result = clientapi_cpanel.models.inline_response_200_60_result.inline_response_200_60_result(
                    data = clientapi_cpanel.models.inline_response_200_60_result_data.inline_response_200_60_result_data(
                        ports = [
                            25
                            ], ), 
                    errors = [
                        ''
                        ], 
                    messages = [
                        ''
                        ], 
                    metadata = null, 
                    status = 1, 
                    warnings = [
                        ''
                        ], )
            )
        else:
            return InlineResponse20060(
        )
        """

    def testInlineResponse20060(self):
        """Test InlineResponse20060"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
