# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.inline_response200575 import InlineResponse200575

class TestInlineResponse200575(unittest.TestCase):
    """InlineResponse200575 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineResponse200575:
        """Test InlineResponse200575
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineResponse200575`
        """
        model = InlineResponse200575()
        if include_optional:
            return InlineResponse200575(
                apiversion = 3,
                func = 'start',
                module = 'WordPressRestore',
                result = clientapi_cpanel.models.inline_response_200_575_result.inline_response_200_575_result(
                    data = clientapi_cpanel.models.inline_response_200_575_result_data.inline_response_200_575_result_data(
                        restore_id = 'example.com__2018-11-15T08:03:22-0600', ), 
                    errors = [
                        ''
                        ], 
                    messages = [
                        ''
                        ], 
                    metadata = null, 
                    status = 1, 
                    warnings = [
                        ''
                        ], )
            )
        else:
            return InlineResponse200575(
        )
        """

    def testInlineResponse200575(self):
        """Test InlineResponse200575"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
