# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.api.subaccount_management_api import SubaccountManagementApi


class TestSubaccountManagementApi(unittest.TestCase):
    """SubaccountManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SubaccountManagementApi()

    def tearDown(self) -> None:
        pass

    def test_check_account_conflicts(self) -> None:
        """Test case for check_account_conflicts

        Return Subaccounts and service accounts conflicts
        """
        pass

    def test_dismiss_merge(self) -> None:
        """Test case for dismiss_merge

        Remove service account link request
        """
        pass

    def test_edit_user(self) -> None:
        """Test case for edit_user

        Update Subaccount settings
        """
        pass

    def test_lookup_service_account(self) -> None:
        """Test case for lookup_service_account

        Return service account's information
        """
        pass

    def test_lookup_user(self) -> None:
        """Test case for lookup_user

        Return Subaccount's information
        """
        pass

    def test_merge_service_account(self) -> None:
        """Test case for merge_service_account

        Register service account to Subaccount
        """
        pass

    def test_unlink_service_account(self) -> None:
        """Test case for unlink_service_account

        Unregister service account from Subaccount
        """
        pass

    def test_user_manager_create_user(self) -> None:
        """Test case for user_manager_create_user

        Create Subaccount
        """
        pass

    def test_user_manager_delete_user(self) -> None:
        """Test case for user_manager_delete_user

        Delete Subaccount
        """
        pass

    def test_user_manager_list_users(self) -> None:
        """Test case for user_manager_list_users

        Return cPanel account's Subaccounts
        """
        pass


if __name__ == '__main__':
    unittest.main()
