# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.api.lang_php_api import LangPHPApi


class TestLangPHPApi(unittest.TestCase):
    """LangPHPApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LangPHPApi()

    def tearDown(self) -> None:
        pass

    def test_php_get_domain_handler(self) -> None:
        """Test case for php_get_domain_handler

        Return PHP version's handler
        """
        pass

    def test_php_get_impacted_domains(self) -> None:
        """Test case for php_get_impacted_domains

        Return domains that shared PHP configuration
        """
        pass

    def test_php_get_installed_versions(self) -> None:
        """Test case for php_get_installed_versions

        Return installed PHP versions
        """
        pass

    def test_php_get_system_default_version(self) -> None:
        """Test case for php_get_system_default_version

        Return default PHP version
        """
        pass

    def test_php_get_vhost_versions(self) -> None:
        """Test case for php_get_vhost_versions

        Return virtual host's PHP version
        """
        pass

    def test_php_ini_get_user_basic_directives(self) -> None:
        """Test case for php_ini_get_user_basic_directives

        Return basic PHP directives
        """
        pass

    def test_php_ini_get_user_content(self) -> None:
        """Test case for php_ini_get_user_content

        Return virtual host's php.ini content
        """
        pass

    def test_php_ini_get_user_paths(self) -> None:
        """Test case for php_ini_get_user_paths

        Return php.ini file paths
        """
        pass

    def test_php_ini_set_user_basic_directives(self) -> None:
        """Test case for php_ini_set_user_basic_directives

        Update basic PHP directives
        """
        pass

    def test_php_ini_set_user_content(self) -> None:
        """Test case for php_ini_set_user_content

        Update virtual host's php.ini content
        """
        pass

    def test_php_set_vhost_versions(self) -> None:
        """Test case for php_set_vhost_versions

        Update virtual host's PHP version
        """
        pass


if __name__ == '__main__':
    unittest.main()
