# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.inline_response20038 import InlineResponse20038

class TestInlineResponse20038(unittest.TestCase):
    """InlineResponse20038 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineResponse20038:
        """Test InlineResponse20038
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineResponse20038`
        """
        model = InlineResponse20038()
        if include_optional:
            return InlineResponse20038(
                apiversion = 3,
                func = 'set_forwarders',
                module = 'BoxTrapper',
                result = clientapi_cpanel.models.inline_response_200_35_result.inline_response_200_35_result(
                    data = clientapi_cpanel.models.data.data(), 
                    errors = [
                        ''
                        ], 
                    messages = [
                        ''
                        ], 
                    metadata = null, 
                    status = 1, 
                    warnings = [
                        ''
                        ], )
            )
        else:
            return InlineResponse20038(
        )
        """

    def testInlineResponse20038(self):
        """Test InlineResponse20038"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
