# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.api.auto_generated_ssl_certificates_api import AutoGeneratedSSLCertificatesApi


class TestAutoGeneratedSSLCertificatesApi(unittest.TestCase):
    """AutoGeneratedSSLCertificatesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AutoGeneratedSSLCertificatesApi()

    def tearDown(self) -> None:
        pass

    def test_add_autossl_excluded_domains(self) -> None:
        """Test case for add_autossl_excluded_domains

        Disable AutoSSL for domains
        """
        pass

    def test_get_autossl_excluded_domains(self) -> None:
        """Test case for get_autossl_excluded_domains

        Return AutoSSL disabled domains
        """
        pass

    def test_get_autossl_problems(self) -> None:
        """Test case for get_autossl_problems

        Return domains with AutoSSL problems
        """
        pass

    def test_is_autossl_check_in_progress(self) -> None:
        """Test case for is_autossl_check_in_progress

        Return whether AutoSSL check in progress
        """
        pass

    def test_remove_autossl_excluded_domains(self) -> None:
        """Test case for remove_autossl_excluded_domains

        Enable AutoSSL for specifed domains
        """
        pass

    def test_set_autossl_excluded_domains(self) -> None:
        """Test case for set_autossl_excluded_domains

        Disable AutoSSL for specifed domains
        """
        pass

    def test_start_autossl_check(self) -> None:
        """Test case for start_autossl_check

        Start AutoSSL for current user
        """
        pass


if __name__ == '__main__':
    unittest.main()
