# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.inline_response200529 import InlineResponse200529

class TestInlineResponse200529(unittest.TestCase):
    """InlineResponse200529 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineResponse200529:
        """Test InlineResponse200529
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineResponse200529`
        """
        model = InlineResponse200529()
        if include_optional:
            return InlineResponse200529(
                apiversion = 3,
                func = 'delete_user',
                module = 'UserManager',
                result = clientapi_cpanel.models.inline_response_200_529_result.inline_response_200_529_result(
                    data = clientapi_cpanel.models.inline_response_200_529_result_data.inline_response_200_529_result_data(
                        alternate_email = 'user@example.com', 
                        avatar_url = 'https://img.example.com/avatars/example.jpg', 
                        can_delete = 0, 
                        can_set_password = 1, 
                        can_set_quota = 0, 
                        dismissed = 1, 
                        dismissed_merge_candidates = [
                            None
                            ], 
                        domain = 'example.com', 
                        full_username = 'user@example.com', 
                        guid = 'N4641:EXAMPLE.COM:564CC8A7:A82EA007D8348AC631C0170F9418EC1DEB0D164CC5A722A87C55EF5DD2AD98D4', 
                        has_expired_invite = 0, 
                        has_invite = 0, 
                        has_siblings = 0, 
                        invite_expiration = 1466258282, 
                        issues = [
                            clientapi_cpanel.models.inline_response_200_529_result_data_issues.inline_response_200_529_result_data_issues(
                                area = 'quota', 
                                limit = 1500, 
                                message = 'Your account is over quota.', 
                                service = 'email', 
                                type = 'info', 
                                used = 2000, )
                            ], 
                        merge_candidates = [
                            clientapi_cpanel.models.inline_response_200_529_result_data_merge_candidates.inline_response_200_529_result_data_merge_candidates(
                                alternate_email = '', 
                                avatar_url = '', 
                                can_delete = 56, 
                                can_set_password = 56, 
                                can_set_quota = 56, 
                                dismissed = 56, 
                                domain = '', 
                                full_username = '', 
                                guid = '', 
                                has_expired_invite = 56, 
                                has_invite = 56, 
                                has_siblings = 56, 
                                invite_expiration = 56, 
                                parent_type = '', 
                                phone_number = '', 
                                real_name = '', 
                                services = clientapi_cpanel.models.services.services(), 
                                special = 56, 
                                sub_account_exists = 56, 
                                synced_password = 56, 
                                type = '', 
                                username = '', )
                            ], 
                        parent_type = 'hypothetical', 
                        phone_number = '+15551234567', 
                        real_name = 'John Doe', 
                        services = clientapi_cpanel.models.inline_response_200_529_result_data_services.inline_response_200_529_result_data_services(
                            email = clientapi_cpanel.models.inline_response_200_529_result_data_services_email.inline_response_200_529_result_data_services_email(
                                enabled = 1, 
                                quota = 100, ), 
                            ftp = clientapi_cpanel.models.inline_response_200_529_result_data_services_ftp.inline_response_200_529_result_data_services_ftp(
                                enabled = 0, 
                                homedir = '/account', 
                                quota = 100, ), 
                            webdisk = clientapi_cpanel.models.inline_response_200_529_result_data_services_webdisk.inline_response_200_529_result_data_services_webdisk(
                                enabled = 0, 
                                homedir = '/bob', 
                                perms = 'rw', 
                                private = 0, ), ), 
                        special = 1, 
                        sub_account_exists = 0, 
                        synced_password = 0, 
                        type = 'service', 
                        username = '', ), 
                    errors = [
                        ''
                        ], 
                    messages = [
                        ''
                        ], 
                    metadata = null, 
                    status = 1, 
                    warnings = [
                        ''
                        ], )
            )
        else:
            return InlineResponse200529(
        )
        """

    def testInlineResponse200529(self):
        """Test InlineResponse200529"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
