# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.trace_delivery_response_base import TraceDeliveryResponseBase

class TestTraceDeliveryResponseBase(unittest.TestCase):
    """TraceDeliveryResponseBase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TraceDeliveryResponseBase:
        """Test TraceDeliveryResponseBase
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TraceDeliveryResponseBase`
        """
        model = TraceDeliveryResponseBase()
        if include_optional:
            return TraceDeliveryResponseBase(
                address = 'username@example.com',
                type = 'local_delivery'
            )
        else:
            return TraceDeliveryResponseBase(
        )
        """

    def testTraceDeliveryResponseBase(self):
        """Test TraceDeliveryResponseBase"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
