# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.inline_response200582 import InlineResponse200582

class TestInlineResponse200582(unittest.TestCase):
    """InlineResponse200582 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineResponse200582:
        """Test InlineResponse200582
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineResponse200582`
        """
        model = InlineResponse200582()
        if include_optional:
            return InlineResponse200582(
                apiversion = 3,
                func = 'disable_domains',
                module = 'cPGreyList',
                result = clientapi_cpanel.models.inline_response_200_582_result.inline_response_200_582_result(
                    data = [
                        clientapi_cpanel.models.inline_response_200_582_result_data.inline_response_200_582_result_data(
                            dependencies = ["this.com","that.com","theother.com"], 
                            domain = 'example.com', 
                            enabled = 0, 
                            searchhint = 'this, that, the other', 
                            type = 'main', )
                        ], 
                    errors = [
                        ''
                        ], 
                    messages = [
                        ''
                        ], 
                    metadata = clientapi_cpanel.models.inline_response_200_result_metadata.inline_response_200_result_metadata(
                        transformed = 1, ), 
                    status = 1, 
                    warnings = [
                        ''
                        ], )
            )
        else:
            return InlineResponse200582(
        )
        """

    def testInlineResponse200582(self):
        """Test InlineResponse200582"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
