# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.api.email_dns_settings_api import EmailDNSSettingsApi


class TestEmailDNSSettingsApi(unittest.TestCase):
    """EmailDNSSettingsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EmailDNSSettingsApi()

    def tearDown(self) -> None:
        pass

    def test_add_mx(self) -> None:
        """Test case for add_mx

        Create mail exchanger record
        """
        pass

    def test_change_mx(self) -> None:
        """Test case for change_mx

        Update mail exchanger record
        """
        pass

    def test_delete_mx(self) -> None:
        """Test case for delete_mx

        Delete mail exchanger record
        """
        pass

    def test_disable_dkim(self) -> None:
        """Test case for disable_dkim

        Remove domains' DKIM records
        """
        pass

    def test_email_auth_apply_dmarc(self) -> None:
        """Test case for email_auth_apply_dmarc

        Apply DMARC records to domains.
        """
        pass

    def test_email_auth_remove_dmarc(self) -> None:
        """Test case for email_auth_remove_dmarc

        Remove DMARC record from domain(s)
        """
        pass

    def test_email_auth_validate_current_dmarcs(self) -> None:
        """Test case for email_auth_validate_current_dmarcs

        Validate domains' DMARC records
        """
        pass

    def test_enable_dkim(self) -> None:
        """Test case for enable_dkim

        Enable domains' DKIM records
        """
        pass

    def test_ensure_dkim_keys_exist(self) -> None:
        """Test case for ensure_dkim_keys_exist

        Validate domains' DKIM private keys
        """
        pass

    def test_fetch_dkim_private_keys(self) -> None:
        """Test case for fetch_dkim_private_keys

        Return domains' DKIM private keys
        """
        pass

    def test_install_dkim_private_keys(self) -> None:
        """Test case for install_dkim_private_keys

        Add domains' DKIM record keys
        """
        pass

    def test_install_spf_records(self) -> None:
        """Test case for install_spf_records

        Add domains' SPF records
        """
        pass

    def test_list_mxs(self) -> None:
        """Test case for list_mxs

        Return mail exchanger records
        """
        pass

    def test_validate_current_dkims(self) -> None:
        """Test case for validate_current_dkims

        Validate domains' DKIM records
        """
        pass

    def test_validate_current_ptrs(self) -> None:
        """Test case for validate_current_ptrs

        Validate domains' PTR records
        """
        pass

    def test_validate_current_spfs(self) -> None:
        """Test case for validate_current_spfs

        Validate domains' SPF records
        """
        pass


if __name__ == '__main__':
    unittest.main()
