# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.inline_response2009 import InlineResponse2009

class TestInlineResponse2009(unittest.TestCase):
    """InlineResponse2009 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineResponse2009:
        """Test InlineResponse2009
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineResponse2009`
        """
        model = InlineResponse2009()
        if include_optional:
            return InlineResponse2009(
                apiversion = 3,
                func = 'restore_email_forwarders',
                module = 'Backup',
                result = clientapi_cpanel.models.inline_response_200_9_result.inline_response_200_9_result(
                    data = clientapi_cpanel.models.inline_response_200_9_result_data.inline_response_200_9_result_data(
                        log_id = '2019-08-13T15:10:07Z.1', 
                        log_path = '/home/cpuser/.cpanel/logs/restore-email-forwarders/2019-09-11T18:30:49Z.1.log', 
                        messages = [
                            'The system successfully restored the email forwarders from the 'aliases-example.com.gz' backup.'
                            ], ), 
                    errors = [
                        ''
                        ], 
                    messages = [
                        ''
                        ], 
                    metadata = null, 
                    status = 1, 
                    warnings = [
                        ''
                        ], )
            )
        else:
            return InlineResponse2009(
        )
        """

    def testInlineResponse2009(self):
        """Test InlineResponse2009"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
