# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.inline_response20091 import InlineResponse20091

class TestInlineResponse20091(unittest.TestCase):
    """InlineResponse20091 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineResponse20091:
        """Test InlineResponse20091
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineResponse20091`
        """
        model = InlineResponse20091()
        if include_optional:
            return InlineResponse20091(
                apiversion = 3,
                func = 'disable_dnssec',
                module = 'DNSSEC',
                result = clientapi_cpanel.models.inline_response_200_91_result.inline_response_200_91_result(
                    data = {"disabled":{"example.com":1}}, 
                    errors = [
                        ''
                        ], 
                    messages = [
                        ''
                        ], 
                    metadata = null, 
                    status = 1, 
                    warnings = [
                        ''
                        ], )
            )
        else:
            return InlineResponse20091(
        )
        """

    def testInlineResponse20091(self):
        """Test InlineResponse20091"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
