# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.api.mod_security_api import ModSecurityApi


class TestModSecurityApi(unittest.TestCase):
    """ModSecurityApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ModSecurityApi()

    def tearDown(self) -> None:
        pass

    def test_disable_all_domains(self) -> None:
        """Test case for disable_all_domains

        Disable ModSecurity for all domains
        """
        pass

    def test_disable_domains(self) -> None:
        """Test case for disable_domains

        Disable ModSecurity for selected domains
        """
        pass

    def test_enable_all_domains(self) -> None:
        """Test case for enable_all_domains

        Enable ModSecurity for all domains
        """
        pass

    def test_enable_domains(self) -> None:
        """Test case for enable_domains

        Enable ModSecurity for selected domains
        """
        pass

    def test_has_modsecurity_installed(self) -> None:
        """Test case for has_modsecurity_installed

        Return ModSecurity installation status
        """
        pass

    def test_mod_security_list_domains(self) -> None:
        """Test case for mod_security_list_domains

        Return ModSecurity domains' status
        """
        pass


if __name__ == '__main__':
    unittest.main()
