# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.inline_response200327 import InlineResponse200327

class TestInlineResponse200327(unittest.TestCase):
    """InlineResponse200327 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineResponse200327:
        """Test InlineResponse200327
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineResponse200327`
        """
        model = InlineResponse200327()
        if include_optional:
            return InlineResponse200327(
                apiversion = 3,
                func = 'list_mime',
                module = 'Mime',
                result = clientapi_cpanel.models.inline_response_200_327_result.inline_response_200_327_result(
                    data = [
                        clientapi_cpanel.models.inline_response_200_327_result_data.inline_response_200_327_result_data(
                            extension = '.foo', 
                            origin = 'user', 
                            type = 'application/foo', )
                        ], 
                    errors = [
                        ''
                        ], 
                    messages = [
                        ''
                        ], 
                    metadata = clientapi_cpanel.models.inline_response_200_result_metadata.inline_response_200_result_metadata(
                        transformed = 1, ), 
                    status = 1, 
                    warnings = [
                        ''
                        ], )
            )
        else:
            return InlineResponse200327(
        )
        """

    def testInlineResponse200327(self):
        """Test InlineResponse200327"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
