# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.inline_response200128 import InlineResponse200128

class TestInlineResponse200128(unittest.TestCase):
    """InlineResponse200128 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineResponse200128:
        """Test InlineResponse200128
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineResponse200128`
        """
        model = InlineResponse200128()
        if include_optional:
            return InlineResponse200128(
                apiversion = 3,
                func = 'browse_mailbox',
                module = 'Email',
                result = clientapi_cpanel.models.inline_response_200_128_result.inline_response_200_128_result(
                    data = [
                        clientapi_cpanel.models.inline_response_200_128_result_data.inline_response_200_128_result_data(
                            depth = 2, 
                            file = 'archive', 
                            fullpath = '/home/example/mail/archive', 
                            isleaf = 0, 
                            ismailbox = 0, 
                            mtime = 1413398866, 
                            path = '/home/example/mail', 
                            relpath = '/archive', 
                            type = 'dir', )
                        ], 
                    errors = [
                        ''
                        ], 
                    messages = [
                        ''
                        ], 
                    metadata = clientapi_cpanel.models.inline_response_200_result_metadata.inline_response_200_result_metadata(
                        transformed = 1, ), 
                    status = 1, 
                    warnings = [
                        ''
                        ], )
            )
        else:
            return InlineResponse200128(
        )
        """

    def testInlineResponse200128(self):
        """Test InlineResponse200128"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
