# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.service_account import ServiceAccount

class TestServiceAccount(unittest.TestCase):
    """ServiceAccount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceAccount:
        """Test ServiceAccount
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceAccount`
        """
        model = ServiceAccount()
        if include_optional:
            return ServiceAccount(
                alternate_email = 'user@example.com',
                avatar_url = 'https://img.example.com/avatars/example.jpg',
                can_delete = 0,
                can_set_password = 1,
                can_set_quota = 0,
                dismissed = 1,
                domain = 'example.com',
                full_username = 'user@example.com',
                guid = 'N4641:EXAMPLE.COM:564CC8A7:A82EA007D8348AC631C0170F9418EC1DEB0D164CC5A722A87C55EF5DD2AD98D4',
                has_siblings = 0,
                issues = [
                    clientapi_cpanel.models.service_account_issues.ServiceAccount_issues(
                        area = 'quota', 
                        limit = 1500, 
                        message = 'Your account is over quota.', 
                        service = 'email', 
                        type = 'info', 
                        used = 2000, )
                    ],
                merge_candidates = [
                    clientapi_cpanel.models.service_account.ServiceAccount(
                        alternate_email = 'user@example.com', 
                        avatar_url = 'https://img.example.com/avatars/example.jpg', 
                        can_delete = 0, 
                        can_set_password = 1, 
                        can_set_quota = 0, 
                        dismissed = 1, 
                        domain = 'example.com', 
                        full_username = 'user@example.com', 
                        guid = 'N4641:EXAMPLE.COM:564CC8A7:A82EA007D8348AC631C0170F9418EC1DEB0D164CC5A722A87C55EF5DD2AD98D4', 
                        has_siblings = 0, 
                        issues = [
                            clientapi_cpanel.models.service_account_issues.ServiceAccount_issues(
                                area = 'quota', 
                                limit = 1500, 
                                message = 'Your account is over quota.', 
                                service = 'email', 
                                type = 'info', 
                                used = 2000, )
                            ], 
                        merge_candidates = [
                            clientapi_cpanel.models.service_account.ServiceAccount(
                                alternate_email = 'user@example.com', 
                                avatar_url = 'https://img.example.com/avatars/example.jpg', 
                                can_delete = 0, 
                                can_set_password = 1, 
                                can_set_quota = 0, 
                                dismissed = 1, 
                                domain = 'example.com', 
                                full_username = 'user@example.com', 
                                guid = 'N4641:EXAMPLE.COM:564CC8A7:A82EA007D8348AC631C0170F9418EC1DEB0D164CC5A722A87C55EF5DD2AD98D4', 
                                has_siblings = 0, 
                                parent_type = 'hypothetical', 
                                phone_number = '+15551234567', 
                                real_name = 'John Doe', 
                                services = clientapi_cpanel.models.service_account_services.ServiceAccount_services(
                                    email = clientapi_cpanel.models.service_account_services_email.ServiceAccount_services_email(
                                        enabled = 1, 
                                        quota = 100, ), 
                                    ftp = clientapi_cpanel.models.service_account_services_ftp.ServiceAccount_services_ftp(
                                        enabled = 0, 
                                        homedir = '/subaccount', 
                                        quota = 100, ), 
                                    special = 1, 
                                    webdisk = clientapi_cpanel.models.service_account_services_webdisk.ServiceAccount_services_webdisk(
                                        enabled = 0, 
                                        enabledigest = 0, 
                                        homedir = '/bob', 
                                        perms = 'rw', 
                                        private = 0, ), ), 
                                special = 0, 
                                sub_account_exists = 0, 
                                synced_password = 0, 
                                type = 'sub', 
                                username = 'example', )
                            ], 
                        parent_type = 'hypothetical', 
                        phone_number = '+15551234567', 
                        real_name = 'John Doe', 
                        services = clientapi_cpanel.models.service_account_services.ServiceAccount_services(
                            special = 1, ), 
                        special = 0, 
                        sub_account_exists = 0, 
                        synced_password = 0, 
                        type = 'sub', 
                        username = 'example', )
                    ],
                parent_type = 'hypothetical',
                phone_number = '+15551234567',
                real_name = 'John Doe',
                services = clientapi_cpanel.models.service_account_services.ServiceAccount_services(
                    email = clientapi_cpanel.models.service_account_services_email.ServiceAccount_services_email(
                        enabled = 1, 
                        quota = 100, ), 
                    ftp = clientapi_cpanel.models.service_account_services_ftp.ServiceAccount_services_ftp(
                        enabled = 0, 
                        homedir = '/subaccount', 
                        quota = 100, ), 
                    special = 1, 
                    webdisk = clientapi_cpanel.models.service_account_services_webdisk.ServiceAccount_services_webdisk(
                        enabled = 0, 
                        enabledigest = 0, 
                        homedir = '/bob', 
                        perms = 'rw', 
                        private = 0, ), ),
                special = 0,
                sub_account_exists = 0,
                synced_password = 0,
                type = 'sub',
                username = 'example'
            )
        else:
            return ServiceAccount(
        )
        """

    def testServiceAccount(self):
        """Test ServiceAccount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
