# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.inline_response20057 import InlineResponse20057

class TestInlineResponse20057(unittest.TestCase):
    """InlineResponse20057 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineResponse20057:
        """Test InlineResponse20057
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineResponse20057`
        """
        model = InlineResponse20057()
        if include_optional:
            return InlineResponse20057(
                apiversion = 3,
                func = 'doimport',
                module = 'CSVImport',
                result = clientapi_cpanel.models.inline_response_200_57_result.inline_response_200_57_result(
                    data = clientapi_cpanel.models.inline_response_200_57_result_data.inline_response_200_57_result_data(
                        results = [{"email":"j.doe@example.com","reason":"OK","status":1,"type":"email"},{"email":"jdoe@example.com","reason":"The account jdoe@example.com already exists!","status":0,"type":"email"}], ), 
                    errors = ["1 error(s) were encountered while importing accounts."], 
                    messages = [
                        ''
                        ], 
                    metadata = null, 
                    status = 0, 
                    warnings = [
                        ''
                        ], )
            )
        else:
            return InlineResponse20057(
        )
        """

    def testInlineResponse20057(self):
        """Test InlineResponse20057"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
