# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.inline_response20055 import InlineResponse20055

class TestInlineResponse20055(unittest.TestCase):
    """InlineResponse20055 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineResponse20055:
        """Test InlineResponse20055
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineResponse20055`
        """
        model = InlineResponse20055()
        if include_optional:
            return InlineResponse20055(
                apiversion = 3,
                func = 'remove_delegate',
                module = 'CPDAVD',
                result = clientapi_cpanel.models.inline_response_200_55_result.inline_response_200_55_result(
                    data = clientapi_cpanel.models.inline_response_200_55_result_data.inline_response_200_55_result_data(
                        shared = 1, ), 
                    errors = [
                        ''
                        ], 
                    messages = [
                        ''
                        ], 
                    metadata = null, 
                    status = 1, 
                    warnings = [
                        ''
                        ], )
            )
        else:
            return InlineResponse20055(
        )
        """

    def testInlineResponse20055(self):
        """Test InlineResponse20055"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
