# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.trace_delivery_response_command_destinations import TraceDeliveryResponseCommandDestinations

class TestTraceDeliveryResponseCommandDestinations(unittest.TestCase):
    """TraceDeliveryResponseCommandDestinations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TraceDeliveryResponseCommandDestinations:
        """Test TraceDeliveryResponseCommandDestinations
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TraceDeliveryResponseCommandDestinations`
        """
        model = TraceDeliveryResponseCommandDestinations()
        if include_optional:
            return TraceDeliveryResponseCommandDestinations(
                command = '/usr/local/cpanel/bin/autorespond user@example.com /home/cpmailuser/.autorespond',
                type = 'local_delivery'
            )
        else:
            return TraceDeliveryResponseCommandDestinations(
        )
        """

    def testTraceDeliveryResponseCommandDestinations(self):
        """Test TraceDeliveryResponseCommandDestinations"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
