# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.inline_response200237 import InlineResponse200237

class TestInlineResponse200237(unittest.TestCase):
    """InlineResponse200237 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineResponse200237:
        """Test InlineResponse200237
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineResponse200237`
        """
        model = InlineResponse200237()
        if include_optional:
            return InlineResponse200237(
                apiversion = 3,
                func = 'get_file_content',
                module = 'Fileman',
                result = clientapi_cpanel.models.inline_response_200_237_result.inline_response_200_237_result(
                    data = clientapi_cpanel.models.inline_response_200_237_result_data.inline_response_200_237_result_data(
                        content = '[B@65a19604', 
                        dir = '/home/user/public_html', 
                        filename = 'example.html', 
                        from_char = 'UTF-8', 
                        from_charset = null, 
                        path = '/home/user/public_html/example.html', 
                        to_char = 'UTF-8', 
                        to_charset = null, ), 
                    errors = [
                        ''
                        ], 
                    messages = [
                        ''
                        ], 
                    metadata = null, 
                    status = 1, 
                    warnings = [
                        ''
                        ], )
            )
        else:
            return InlineResponse200237(
        )
        """

    def testInlineResponse200237(self):
        """Test InlineResponse200237"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
