# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.inline_response200109 import InlineResponse200109

class TestInlineResponse200109(unittest.TestCase):
    """InlineResponse200109 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineResponse200109:
        """Test InlineResponse200109
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineResponse200109`
        """
        model = InlineResponse200109()
        if include_optional:
            return InlineResponse200109(
                apiversion = 3,
                func = 'list_directories',
                module = 'DirectoryProtection',
                result = clientapi_cpanel.models.inline_response_200_109_result.inline_response_200_109_result(
                    data = clientapi_cpanel.models.inline_response_200_109_result_data.inline_response_200_109_result_data(
                        children = [
                            clientapi_cpanel.models.inline_response_200_109_result_data_children.inline_response_200_109_result_data_children(
                                path = '/home/example/example.com/cgi-bin', 
                                state = clientapi_cpanel.models.inline_response_200_109_result_data_state.inline_response_200_109_result_data_state(
                                    has_leech_protection = 1, ), )
                            ], 
                        current = clientapi_cpanel.models.inline_response_200_109_result_data_current.inline_response_200_109_result_data_current(
                            path = '/home/example/example.com', ), 
                        home = clientapi_cpanel.models.inline_response_200_109_result_data_home.inline_response_200_109_result_data_home(
                            path = '/home/example', ), 
                        parent = clientapi_cpanel.models.inline_response_200_109_result_data_parent.inline_response_200_109_result_data_parent(
                            path = '/home/example', ), ), 
                    errors = [
                        ''
                        ], 
                    messages = [
                        ''
                        ], 
                    metadata = null, 
                    status = 1, 
                    warnings = [
                        ''
                        ], )
            )
        else:
            return InlineResponse200109(
        )
        """

    def testInlineResponse200109(self):
        """Test InlineResponse200109"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
