# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.inline_response200364 import InlineResponse200364

class TestInlineResponse200364(unittest.TestCase):
    """InlineResponse200364 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineResponse200364:
        """Test InlineResponse200364
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineResponse200364`
        """
        model = InlineResponse200364()
        if include_optional:
            return InlineResponse200364(
                apiversion = 3,
                func = 'reset_cache_config',
                module = 'NginxCaching',
                result = clientapi_cpanel.models.inline_response_200_361_result.inline_response_200_361_result(
                    data = null, 
                    errors = [
                        ''
                        ], 
                    messages = [
                        ''
                        ], 
                    metadata = null, 
                    status = 1, 
                    warnings = [
                        ''
                        ], )
            )
        else:
            return InlineResponse200364(
        )
        """

    def testInlineResponse200364(self):
        """Test InlineResponse200364"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
