# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.inline_response200348 import InlineResponse200348

class TestInlineResponse200348(unittest.TestCase):
    """InlineResponse200348 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineResponse200348:
        """Test InlineResponse200348
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineResponse200348`
        """
        model = InlineResponse200348()
        if include_optional:
            return InlineResponse200348(
                apiversion = 3,
                func = 'get_server_information',
                module = 'Mysql',
                result = clientapi_cpanel.models.inline_response_200_348_result.inline_response_200_348_result(
                    data = clientapi_cpanel.models.inline_response_200_348_result_data.inline_response_200_348_result_data(
                        host = null, 
                        is_remote = 1, 
                        version = '5.6.23', ), 
                    errors = [
                        ''
                        ], 
                    messages = [
                        ''
                        ], 
                    metadata = null, 
                    status = 1, 
                    warnings = [
                        ''
                        ], )
            )
        else:
            return InlineResponse200348(
        )
        """

    def testInlineResponse200348(self):
        """Test InlineResponse200348"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
