# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.inline_response200326 import InlineResponse200326

class TestInlineResponse200326(unittest.TestCase):
    """InlineResponse200326 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineResponse200326:
        """Test InlineResponse200326
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineResponse200326`
        """
        model = InlineResponse200326()
        if include_optional:
            return InlineResponse200326(
                apiversion = 3,
                func = 'list_hotlinks',
                module = 'Mime',
                result = clientapi_cpanel.models.inline_response_200_326_result.inline_response_200_326_result(
                    data = clientapi_cpanel.models.inline_response_200_326_result_data.inline_response_200_326_result_data(
                        allow_null = 1, 
                        extensions = 'jpg,jpeg,gif,png,bmp', 
                        redirect_url = 'http://redirect.example.com/', 
                        state = 'disabled', 
                        urls = [
                            'http://example.com/'
                            ], ), 
                    errors = [
                        ''
                        ], 
                    messages = [
                        ''
                        ], 
                    metadata = null, 
                    status = 1, 
                    warnings = [
                        ''
                        ], )
            )
        else:
            return InlineResponse200326(
        )
        """

    def testInlineResponse200326(self):
        """Test InlineResponse200326"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
