# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_cpanel.models.inline_response200104 import InlineResponse200104

class TestInlineResponse200104(unittest.TestCase):
    """InlineResponse200104 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineResponse200104:
        """Test InlineResponse200104
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineResponse200104`
        """
        model = InlineResponse200104()
        if include_optional:
            return InlineResponse200104(
                apiversion = 3,
                func = 'configure_directory_protection',
                module = 'DirectoryPrivacy',
                result = clientapi_cpanel.models.inline_response_200_104_result.inline_response_200_104_result(
                    data = clientapi_cpanel.models.inline_response_200_104_result_data.inline_response_200_104_result_data(
                        auth_name = 'protectandserve', 
                        auth_type = 'Basic', 
                        passwd_file = '/home/example/.htpasswds/example.com/passwd', 
                        protected = 1, ), 
                    errors = [
                        ''
                        ], 
                    messages = [
                        ''
                        ], 
                    metadata = null, 
                    status = 1, 
                    warnings = [
                        ''
                        ], )
            )
        else:
            return InlineResponse200104(
        )
        """

    def testInlineResponse200104(self):
        """Test InlineResponse200104"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
