# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from clientapi_cpanel.models.market_provider_product_meta_data import MarketProviderProductMetaData
from clientapi_cpanel.models.ssl_market_provider_product_meta_data import SSLMarketProviderProductMetaData
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

MARKETPROVIDERPRODUCTMETADATATYPE_ANY_OF_SCHEMAS = ["MarketProviderProductMetaData", "SSLMarketProviderProductMetaData"]

class MarketProviderProductMetaDataType(BaseModel):
    """
    MarketProviderProductMetaDataType
    """

    # data type: MarketProviderProductMetaData
    anyof_schema_1_validator: Optional[MarketProviderProductMetaData] = None
    # data type: SSLMarketProviderProductMetaData
    anyof_schema_2_validator: Optional[SSLMarketProviderProductMetaData] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[MarketProviderProductMetaData, SSLMarketProviderProductMetaData]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "MarketProviderProductMetaData", "SSLMarketProviderProductMetaData" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = MarketProviderProductMetaDataType.model_construct()
        error_messages = []
        # validate data type: MarketProviderProductMetaData
        if not isinstance(v, MarketProviderProductMetaData):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MarketProviderProductMetaData`")
        else:
            return v

        # validate data type: SSLMarketProviderProductMetaData
        if not isinstance(v, SSLMarketProviderProductMetaData):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SSLMarketProviderProductMetaData`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in MarketProviderProductMetaDataType with anyOf schemas: MarketProviderProductMetaData, SSLMarketProviderProductMetaData. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[MarketProviderProductMetaData] = None
        try:
            instance.actual_instance = MarketProviderProductMetaData.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[SSLMarketProviderProductMetaData] = None
        try:
            instance.actual_instance = SSLMarketProviderProductMetaData.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into MarketProviderProductMetaDataType with anyOf schemas: MarketProviderProductMetaData, SSLMarketProviderProductMetaData. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], MarketProviderProductMetaData, SSLMarketProviderProductMetaData]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


