# coding: utf-8

"""
    cPanel UAPI

    UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.

    The version of the OpenAPI document: 11.125.9901.267
    Contact: cs@cpanel.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from clientapi_cpanel.models.restore_not_in_progress_last_outcome import RestoreNotInProgressLastOutcome
from typing import Optional, Set
from typing_extensions import Self

class RestoreNotInProgress(BaseModel):
    """
    RestoreNotInProgress
    """ # noqa: E501
    any_running: Optional[StrictInt] = Field(default=None, description="Whether the system is processing a backup restoration.  * `0` - No restoration in progress. This is the only possible value.")
    last_outcome: Optional[RestoreNotInProgressLastOutcome] = None
    sites: Optional[Dict[str, Any]] = Field(default=None, description="Information about the site that the system is actively restoring.  **Note:**  * This function returns an empty array when there is **not** an active backup restoration. This is the only possible value. * We have not implemented this return.")
    __properties: ClassVar[List[str]] = ["any_running", "last_outcome", "sites"]

    @field_validator('any_running')
    def any_running_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([0]):
            raise ValueError("must be one of enum values (0)")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RestoreNotInProgress from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of last_outcome
        if self.last_outcome:
            _dict['last_outcome'] = self.last_outcome.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RestoreNotInProgress from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "any_running": obj.get("any_running"),
            "last_outcome": RestoreNotInProgressLastOutcome.from_dict(obj["last_outcome"]) if obj.get("last_outcome") is not None else None,
            "sites": obj.get("sites")
        })
        return _obj


